package exceptionhandling;

public class ExceptionHandling {

	public static void main(String[] args) {
		try {
		int c=1/0;
		}
		catch(ArithmeticException a) {
			
		}
		//catch(exp2 ref_variable2){  }//multiple catches possible
	}

}
